wandb_version: 1

batch_size:
  value: 1024
clip_range:
  value: 0.1
ent_coef:
  value: 1.0190810329668596
episode_length:
  value: 3200
gae_lambda:
  value: 0.8926239487394768
gamma:
  value: 0.9954361036217816
learning_rate:
  value: 1.0e-05
n_epochs:
  value: 2
n_steps:
  value: 16384
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 42
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 1024
  - 512
