wandb_version: 1

batch_size:
  value: 4096
clip_range:
  value: 0.1
ent_coef:
  value: 1.012168404018491
episode_length:
  value: 3200
gae_lambda:
  value: 0.8981589696500303
gamma:
  value: 0.9885019333779658
learning_rate:
  value: 1.0e-05
n_epochs:
  value: 2
n_steps:
  value: 4096
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 7
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 4000
  - 1000
