wandb_version: 1

batch_size:
  value: 4096
clip_range:
  value: 0.1
ent_coef:
  value: 1.0264952546704802
episode_length:
  value: 3200
gae_lambda:
  value: 0.9479156503516156
gamma:
  value: 0.964244597646757
learning_rate:
  value: 0.0003
n_epochs:
  value: 8
n_steps:
  value: 4096
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 42
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 2048
  - 512
