wandb_version: 1

batch_size:
  value: 2048
clip_range:
  value: 0.3
ent_coef:
  value: 1.023257162343199
episode_length:
  value: 3200
gae_lambda:
  value: 0.8536176890102977
gamma:
  value: 0.9926164269068496
learning_rate:
  value: 0.0005
n_epochs:
  value: 8
n_steps:
  value: 16384
pi_nn:
  value:
  - 1024
  - 512
seed:
  value: 42
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 1024
  - 512
