wandb_version: 1

batch_size:
  value: 1024
clip_range:
  value: 0.3
ent_coef:
  value: 1.004411270603176
episode_length:
  value: 3200
gae_lambda:
  value: 0.8679205219269513
gamma:
  value: 0.9613465197372608
learning_rate:
  value: 0.0003
n_epochs:
  value: 8
n_steps:
  value: 2048
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 2
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 1024
  - 512
