_wandb:
    value:
        cli_version: 0.22.0
        e:
            ik1nv9zsrkzrgz4gee89b832i6pwseck:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                args:
                    - --sweep
                    - sweep.yaml
                    - --count
                    - "30"
                codePath: sweep.py
                codePathLocal: sweep.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "458683609088"
                email: mikkeljanusdahl@gmail.com
                executable: /Users/mikkeldahl/green_scheduler_v2/.venv/bin/python
                git:
                    commit: 898057752883a9c89223cdf4ff508febbd337cdf
                    remote: https://github.com/dadyownes15/green-hpc-scheduler.git
                host: Mikkels-MacBook-Pro-2.local
                memory:
                    total: "17179869184"
                os: macOS-13.6.9-arm64-arm-64bit
                program: /Users/mikkeldahl/green_scheduler_v2/sweep.py
                python: CPython 3.12.2
                root: /Users/mikkeldahl/green_scheduler_v2
                startedAt: "2025-09-23T14:17:59.668132Z"
                writerId: ik1nv9zsrkzrgz4gee89b832i6pwseck
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
                - 22
            "4": 3.12.2
            "5": 0.22.0
            "12": 0.22.0
            "13": darwin-arm64
alpha:
    value: 0
base_line_wait_carbon_penality:
    value: 0.01
batch_size:
    value: 4096
bounded_slowdown_threshold:
    value: 10
carbon_year:
    value: 2021
clip_range:
    value: 0.3
constant_power_per_processor:
    value: 500
custom_intensity:
    value: false
delay_time_list:
    value:
        - 300
        - 600
        - 1200
        - 1800
        - 2400
        - 3000
        - 3600
delay_time_list_length:
    value: 3
ent_coef:
    value: 1.0005059424259866
episode_length:
    value: 3200
eta:
    value: 10
gae_lambda:
    value: 0.8800038448870228
gamma:
    value: 0.9932584630603112
green_feature_constant:
    value: 8
green_feature_pr_timeslot:
    value: 1
green_forecast_length:
    value: 24
idle_power:
    value: 15
job_feature:
    value: 5
learning_rate:
    value: 0.0001
max_green:
    value: 19000
max_power:
    value: 19000
max_queue_size:
    value: 256
max_requested_processors:
    value: 256
max_run_time:
    value: 162754
max_wait_n_jobs:
    value: 3
max_wait_time:
    value: 200000
n_epochs:
    value: 2
n_steps:
    value: 32768
pi_nn:
    value:
        - 2048
        - 512
procs_per_node:
    value: 1
reward_type:
    value: wait_relative_ems
run_feature:
    value: 2
run_win_length:
    value: 64
seed:
    value: 42
total_timesteps:
    value: 300000
use_constant_power:
    value: true
vf_nn:
    value:
        - 2048
        - 512
