wandb_version: 1

batch_size:
  value: 2048
clip_range:
  value: 0.2
ent_coef:
  value: 1.0287777990206932
episode_length:
  value: 3200
gae_lambda:
  value: 0.9054949216476108
gamma:
  value: 0.9798366031106008
learning_rate:
  value: 0.0005
n_epochs:
  value: 2
n_steps:
  value: 4096
pi_nn:
  value:
  - 2048
  - 512
seed:
  value: 7
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 2048
  - 512
