wandb_version: 1

batch_size:
  value: 2048
clip_range:
  value: 0.2
ent_coef:
  value: 1.0278045256034858
episode_length:
  value: 3200
gae_lambda:
  value: 0.9620357025482076
gamma:
  value: 0.9703941485903232
learning_rate:
  value: 5.0e-05
n_epochs:
  value: 1
n_steps:
  value: 4096
pi_nn:
  value:
  - 1024
  - 512
seed:
  value: 7
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 2048
  - 512
