wandb_version: 1

batch_size:
  value: 1024
clip_range:
  value: 0.1
ent_coef:
  value: 1.016233415881405
episode_length:
  value: 3200
gae_lambda:
  value: 0.907630764339086
gamma:
  value: 0.9858518329995618
learning_rate:
  value: 1.0e-05
n_epochs:
  value: 1
n_steps:
  value: 8192
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 2
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 4000
  - 1000
