wandb_version: 1

batch_size:
  value: 4096
clip_range:
  value: 0.2
ent_coef:
  value: 1.0063754776436755
episode_length:
  value: 3200
gae_lambda:
  value: 0.9210904627744688
gamma:
  value: 0.983604910873041
learning_rate:
  value: 0.0005
n_epochs:
  value: 8
n_steps:
  value: 8192
pi_nn:
  value:
  - 2048
  - 512
seed:
  value: 2
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 2048
  - 512
