wandb_version: 1

batch_size:
  value: 4096
clip_range:
  value: 0.2
ent_coef:
  value: 1.0430649864365231
episode_length:
  value: 3200
gae_lambda:
  value: 0.8978004104013451
gamma:
  value: 0.9682880232638476
learning_rate:
  value: 0.0005
n_epochs:
  value: 8
n_steps:
  value: 8192
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 7
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 1024
  - 512
