wandb_version: 1

batch_size:
  value: 4096
clip_range:
  value: 0.3
ent_coef:
  value: 1.0245564719305011
episode_length:
  value: 3200
gae_lambda:
  value: 0.8616016217297415
gamma:
  value: 0.9880395282830516
learning_rate:
  value: 1.0e-05
n_epochs:
  value: 4
n_steps:
  value: 2048
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 42
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 4000
  - 1000
