wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 1.0309500671086451
episode_length:
  value: 3200
gae_lambda:
  value: 0.8848412865217534
gamma:
  value: 0.9717320729833688
learning_rate:
  value: 1.0e-05
n_epochs:
  value: 2
n_steps:
  value: 2048
pi_nn:
  value:
  - 4000
  - 1000
seed:
  value: 7
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 1024
  - 512
