_wandb:
    value:
        cli_version: 0.22.0
        e:
            0dovr5xt7k1ijf3mmpd4885qjtdzx8j3:
                codePath: sweep.py
                codePathLocal: sweep.py
                email: mikkeljanusdahl@gmail.com
                executable: /Users/mikkeldahl/green_scheduler_v2/.venv/bin/python
                git:
                    commit: d2c4cec3d8e7c55dbada104b4f16ede49d23e934
                    remote: https://github.com/dadyownes15/green-hpc-scheduler.git
                host: Mikkels-MBP-2
                os: macOS-13.6.9-arm64-arm-64bit
                program: /Users/mikkeldahl/green_scheduler_v2/sweep.py
                python: CPython 3.12.2
                root: /Users/mikkeldahl/green_scheduler_v2
                startedAt: "2025-09-23T11:46:20.779068Z"
                writerId: 0dovr5xt7k1ijf3mmpd4885qjtdzx8j3
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 24
            "4": 3.12.2
            "5": 0.22.0
            "12": 0.22.0
            "13": darwin-arm64
batch_size:
    value: 2048
clip_range:
    value: 0.1
ent_coef:
    value: 0.01
episode_length:
    value: 3200
gae_lambda:
    value: 0.97
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
n_epochs:
    value: 1
n_steps:
    value: 16538
pi_nn:
    value:
        - 4000
        - 1000
seed:
    value: 2
total_timesteps:
    value: 1000000
vf_nn:
    value:
        - 4000
        - 1000
