wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 1.0006263015491303
episode_length:
  value: 3200
gae_lambda:
  value: 0.9689190621173946
gamma:
  value: 0.9696560301906968
learning_rate:
  value: 1.0e-05
n_epochs:
  value: 2
n_steps:
  value: 8192
pi_nn:
  value:
  - 2048
  - 512
seed:
  value: 7
total_timesteps:
  value: 300000
vf_nn:
  value:
  - 4000
  - 1000
